behaviors:
  Pacman:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 10000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
#      buffer_init_steps: 0
#      tau: 0.005
#      steps_per_update: 10.0
#      save_replay_buffer: false
#      init_entcoef: 0.5
#      reward_signal_steps_per_update: 10.0
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 100
    max_steps: 30000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 10000
      team_change: 50000
      swap_steps: 1000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
  Ghost:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 10000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
#      buffer_init_steps: 0
#      tau: 0.005
#      steps_per_update: 10.0
#      save_replay_buffer: false
#      init_entcoef: 0.5
#      reward_signal_steps_per_update: 10.0
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 100
    max_steps: 30000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 4000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
